[package]
name = "maud-helpers"
version = "0.7.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = { version = "*", features = ["axum"] }
